## Gráfico de Linhas
Vamos criar um gráfico de linhas para analisar a evolução do preço das ações das empresas Tesla e Apple.

In [3]:
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
ticker = yf.Ticker('TSLA')
df = ticker.history(interval = '1d', start = '2020-01-01')

In [5]:
df.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2020-01-02 00:00:00-05:00,28.299999,28.713333,28.114000,28.684000,142981500,0.0,0.0
2020-01-03 00:00:00-05:00,29.366667,30.266666,29.128000,29.534000,266677500,0.0,0.0
2020-01-06 00:00:00-05:00,29.364668,30.104000,29.333332,30.102667,151995000,0.0,0.0
2020-01-07 00:00:00-05:00,30.760000,31.441999,30.224001,31.270666,268231500,0.0,0.0
2020-01-08 00:00:00-05:00,31.580000,33.232666,31.215334,32.809334,467164500,0.0,0.0

In [6]:
ticker = yf.Ticker('AAPl')
df2 = ticker.history(interval = '1d', start = '2020-01-01')

In [7]:
df2.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2020-01-02 00:00:00-05:00,71.282575,72.331702,71.029923,72.271545,135480400,0.0,0.0
2020-01-03 00:00:00-05:00,71.501542,72.326882,71.345137,71.568916,146322800,0.0,0.0
2020-01-06 00:00:00-05:00,70.693051,72.177699,70.442799,72.139198,118387200,0.0,0.0
2020-01-07 00:00:00-05:00,72.148805,72.403866,71.580935,71.799904,108872000,0.0,0.0
2020-01-08 00:00:00-05:00,71.503945,73.255691,71.503945,72.954910,132079200,0.0,0.0

In [9]:
df['Close AAPL'] = df2['Close']
df.rename(columns= {'Close': 'Close TSLA'}, inplace=True)
df.head()

,Open,High,Low,Close TSLA,Volume,Dividends,Stock Splits,Close AAPL
Date,,,,,,,,
2020-01-02 00:00:00-05:00,28.299999,28.713333,28.114000,28.684000,142981500,0.0,0.0,72.271545
2020-01-03 00:00:00-05:00,29.366667,30.266666,29.128000,29.534000,266677500,0.0,0.0,71.568916
2020-01-06 00:00:00-05:00,29.364668,30.104000,29.333332,30.102667,151995000,0.0,0.0,72.139198
2020-01-07 00:00:00-05:00,30.760000,31.441999,30.224001,31.270666,268231500,0.0,0.0,71.799904
2020-01-08 00:00:00-05:00,31.580000,33.232666,31.215334,32.809334,467164500,0.0,0.0,72.954910

In [ ]:
plt.rcParams['figure.figsize'] = [10,8] 
sns.set_style('darkgrid')
df[['Close']]

Vamos agora utilizar o dataset LifeExpectancy para criar um gráfico de barras.

In [ ]:
df3 =

Nosso gráfico deve permitir comparar a expectativa de vida de homens e mulheres de países africanos.

In [ ]:
df3.plot(x='Countries', kind = 'bar', stacked = False)
plt.tittle('Expectativa de vida nos paises africanos')
plt.xlabel('Paises')
plt.ylabel('Expectativa de vida')
plt.show

Para uma melhor visualização, podemos dividir o dataset. A seguir vamos tomar os 15 primeiros países do dataset.

In [ ]:
df4 = df3.head(15)

df3.plot(x='Countries', kind = 'bar', stacked = False)
plt.tittle('Expectativa de vida nos paises africanos')
plt.xlabel('Paises')
plt.ylabel('Expectativa de vida')
plt.show